Update question 1 (b)

diff --git a/question 1 (b) b/question 1 (b)
--- a/question 1 (b)
+++ b/question 1 (b)
@@ -1,100 +1,76 @@
 #!/usr/bin/bash
-
- 
-
-# Parse command line arguments
-while [[ $# -gt 0 ]]; do
-    key="$1"
-
- 
-
-    case $key in
-        -p|--platform)
-        PLATFORM="$2"
-        shift
-        shift
-        ;;
-        -c|--command)
-        COMMAND="$2"
-        shift
-        shift
-        ;;
-        *)
-        shift
-        ;;
-    esac
+while getopts ":p:c:" opt; do
+  case $opt in
+    p)
+      PLATFORM=$OPTARG
+      ;;
+    c)
+      COMMAND=$OPTARG
+      ;;
+    \?)
+      echo "Invalid option: -$OPTARG" >&2
+      exit 1
+      ;;
+    :)
+      echo "Option -$OPTARG requires an argument." >&2
+      exit 1
+      ;;
+  esac
 done
 
  
 
- 
-
-# Function to deploy pods
-deploy_pods() {
-    local namespace="$1"
-
- 
-
-    # Deploy pods
-    for i in {1..4}; do
-        kubectl -n "$namespace" run pod-$i --image=nginx 
-    done
+if [ -z "$PLATFORM" ] || [ -z "$COMMAND" ]; then
+  echo "Usage: $0 -p platform -c command"
+  exit 1
+fi
 
  
 
-    # Wait for pods to be ready
-    kubectl wait --for=condition=ready pods -n "$namespace" --all
-}
-# Function to create communication between pods in different namespaces
-create_communication() {
-    local source_namespace=$1
-    local target_namespace=$2
+if [ "$PLATFORM" = "minikube" ]; then
+  # Set context to Minikube
+  kubectl config use-context minikube
 
  
 
-    source_pod=$(kubectl get pods -n "$source_namespace" -o=jsonpath='{.items[0].metadata.name}')
-    target_pod=$(kubectl get pods -n "$target_namespace" -o=jsonpath='{.items[0].metadata.name}')
+  if [[ "$COMMAND" = "deploy" || "$COMMAND" = "deploy-complete" ]]; then
+    # Create namespaces
+    kubectl create namespace namespace1
+    kubectl create namespace namespace2
 
  
 
-    kubectl exec -n "$source_namespace" "$source_pod" -- sh -c "curl $target_pod"
-    if [ $? -ne 0 ]; then
-        echo "Error establishing communication between pods"
-    else
-    echo "Communication established between pods"
+   # Create four pods in the first namespace
+  kubectl create deployment pod1-namespace1 --image=nginx --namespace=namespace1
+  kubectl create deployment pod2-namespace1 --image=nginx --namespace=namespace1
+  kubectl create deployment pod3-namespace1 --image=nginx --namespace=namespace1
+  kubectl create deployment pod4-namespace1 --image=nginx --namespace=namespace1
+  # Create four pods in the second namespace
+  kubectl create deployment pod1-namespace2 --image=nginx --namespace=namespace2
+  kubectl create deployment pod2-namespace2 --image=nginx --namespace=namespace2
+  kubectl create deployment pod3-namespace2 --image=nginx --namespace=namespace2
+  kubectl create deployment pod4-namespace2 --image=nginx --namespace=namespace2
+
+ 
+
+ 
+
+    # Creating Service
+    if [ "$COMMAND" = "deploy-complete" ]; then
+    kubectl apply -f service-namespace1.yaml -n namespace1
+    kubectl apply -f service-namespace2.yaml -n namespace2
     fi
-}
+  else
+    echo "Unknown command: $COMMAND"
+    exit 1
+  fi
+else
+  echo "Unsupported platform: $PLATFORM"
+  exit 1
+fi
+ 
 
 
  
 
-# Main script
 
- 
-
-# Create namespaces
-kubectl create namespace namespace1
-kubectl create namespace namespace2
-
- 
-
-# Deploy pods to namespaces
-deploy_pods namespace1
-deploy_pods namespace2
-
- 
-
-# Wait for pods to be ready
-kubectl wait --for=condition=ready pods -n namespace1 --all
-kubectl wait --for=condition=ready pods -n namespace2 --all
-
- 
-
-# Establish communication between pods in different namespaces
-create_communication namespace1 namespace2
-
- 
-
-        echo "Communication established between pods"
-    fi
-}
